### ISSUE TITLE
Add a basic set of useful symbols.

### ISSUE THREAD

**Issue by jlevesy** [Ullaakut/disgo#3]
A cool thing could be to export a set of constants which represents useful symbols usable in terminals.

So we can write something like ...

```
log.Info(logger.Trace("Connecting to database..."))
log.Infoln(logger.Success(symbols.CheckMark))
```

WDYT ?

**Comment by Ullaakut** [comment]
I'd suggest adding the following UTF-8 symbols:

- `✔` (`\xe2\x9c\x94`) named `symbols.CheckMark`
- `✖` (`\xe2\x9c\x96`) named `symbols.CrossMark`
- `❮` (`\xe2\x9d\xae`) named `symbols.LeftArrow`
- `❯` (`\xe2\x9d\xaf`) named `symbols.RightArrow`
- `▶` (`\xE2\x96\xB6`) named `symbols.RightTriangle`
- `◀` (`\xE2\x97\x80`) named `symbols.LeftTriangle`

You can find more of them [here](https://apps.timwhitlock.info/emoji/tables/unicode), let me know if there are others that you are considering :)

I'd suggest only allowing those that are not colored in the `Native` columns, since they don't carry color information and thus can be colored by the user depending on their use case (they might want a red cross mark, a green check mark, a blue arrow, etc. and they could do so via `logger.Success(symbols.CheckMark)`.
